### ISSUE TITLE
It seems that the DECIMAL converts incorrectly

### ISSUE THREAD

**Issue by klubov** [tmukherjee13/yii2-reverse-migration#4] opened 2016-09-17 13:06 UTC
In table:
...
`price` decimal(6,2) DEFAULT NULL,
...

In migration:
...
'price' => $this->decimal(6),
...

In table after migration:
...
`price` decimal(6) DEFAULT NULL,
...

**Comment by tmukherjee13** [comment] 2016-09-26 19:15
@klubov the issue is fixed now. Please update to get the latest files.

**Closed as completed by tmukherjee13** 2016-09-26 19:15 UTC
